name: Version Bump

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:
  CreateNewTag:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag/create release point
      uses: anothrNick/github-tag-action@1.33.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: none
        RELEASE_BRANCHES: main,master  
        INITIAL_VERSION: 2.0.3
        VERBOSE: true
      id: bump_version
    outputs:
      new_version: ${{ steps.bump_version.outputs.new_tag }}
      
  BuildTargets:
    needs: CreateNewTag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Hello World
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: ${{ needs.CreateNewTag.outputs.new_version }}
#    - name: Repository dispatch tag created event
#      uses: peter-evans/repository-dispatch@v1
#      with:
#        token: ${{ secrets.REPO_ACCESS_TOKEN }}
#        event-type: tag-created
#        client-payload: '{"new_version": "${{ steps.bump_version.outputs.new_tag }}"}'

# wichtig: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token
