name: Version Bump

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:
  Create New Tag:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag/create release point
      uses: anothrNick/github-tag-action@1.33.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: none
        RELEASE_BRANCHES: main,master  
        INITIAL_VERSION: 2.0.3
        VERBOSE: true
      id: bump_version
    - name: Repository dispatch tag created event
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: tag-created
        client-payload: '{"new_version": "${{ steps.bump_version.outputs.new_tag }}"}'
