name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:
  UnixBuild:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake ..
    - name: make
      run: |
        cd build
        make
    - name: testrun
      run: |
        ./build/hello
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/hello
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
#        ls
#        ls build
#        ./hello

#  build-cpp-windows-2019:
#    name: C++/MSVS (windows-2019)

#    runs-on: windows-2019

#    env:
#      wxMSW_VER: 3.1.3
#      WXWIN: c:\wxWidgets-3.1.3

#    steps:
#      - uses: actions/checkout@v2

#      - name: Install wxWidgets
#        run: |
#          mkdir ${env:WXWIN} | Out-Null
#          cd ${env:WXWIN}
#          curl -OL https://github.com/wxWidgets/wxWidgets/releases/download/v${env:wxMSW_VER}/wxWidgets-${env:wxMSW_VER}-headers.7z
#          7z x wxWidgets-${env:wxMSW_VER}-headers.7z
#          curl -OL https://github.com/wxWidgets/wxWidgets/releases/download/v${env:wxMSW_VER}/wxMSW-${env:wxMSW_VER}_vc14x_x64_Dev.7z
#          7z x wxMSW-${env:wxMSW_VER}_vc14x_x64_Dev.7z
#      - name: cmake
#        run: |
#          mkdir build
#          cd build
#          cmake .. -G "Visual Studio 16 2019" -A Win32 -DCMAKE_CONFIGURATION_TYPES=Release
#      - name: make
#        run: |
#          cd build
#          make
        
#  WindowsBuild:

#    runs-on: windows-latest
  
#    steps:
#      - uses: actions/checkout@v2
        
#      - name: Installing vcpkg (windows)
#        run: |
#          cd ..
#          git clone https://github.com/Microsoft/vcpkg.git
#          cd vcpkg
#          git checkout --force 2020.01
#          .\bootstrap-vcpkg.bat
#          .\vcpkg.exe install wxwidgets:x86-windows-static
##      - name: Download a file
##        uses: carlosperate/download-file-action@v1.0.3
##        id: download-poetry
##        with:
##            file-url: 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.4/wxWidgets-3.1.4.zip'
##            file-name: 'wxWidgets-3.1.4.zip'
##            location: './wxWidgets-3.1.4'
##      - name: Print the file path
##        run: echo "The file was downloaded to ${{ steps.download-poetry.outputs.file-path }}"

##      - name: Decompress
##        uses: TonyBogdanov/zip@1.0
##        with:
##            args: unzip -qq ./${{ steps.download-poetry.outputs.file-path }}/wxWidgets-3.1.4.zip -d ./wxwidgets
#      - name: cmake
#        run: |
#          mkdir build
#          cd build
#          cmake .. "-DCMAKE_TOOLCHAIN_FILE=D:/a/NaCl_Configurator/vcpkg/scripts/buildsystems/vcpkg.cmake" -G "Visual Studio 16 2019" -A Win32 -DCMAKE_CONFIGURATION_TYPES=Release
#      - name: make
#        run: |
#          cd build
#          make
