name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:
  UnixBuild:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake ..
    - name: make
      run: |
        cd build
        make
    - name: testrun
      run: |
        chmod +x ./build/hello
        ./build/hello
#    - name: Bump version and push tag/create release point
#      uses: anothrNick/github-tag-action@1.33.0
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        WITH_V: true
#      id: bump_version
#    - name: Upload binaries to release
#      uses: svenstaro/upload-release-action@v2
#      with:
#        repo_token: ${{ secrets.GITHUB_TOKEN }}
#        file: build/hello
#        asset_name: hello_world
#        tag: ${{ steps.bump_version.outputs.new_tag }}
#        overwrite: true
#        body: "Testrelease von Hello World mit CMake"



  build-cpp-windows-2019:
    name: C++/MSVS (windows-2019)

    runs-on: windows-2019
    

    env:
      wxMSW_VER: 3.1.4
      WXWIN: wxWidgets-
#      WXWIN: c:\wxWidgets-

    steps:
      - name: checkout wxWin
        uses: actions/checkout@v2
        with:
          repository: wxWidgets/wxWidgets
          ref: v${{ env.wxMSW_VER }}
          path: ${{ env.WXWIN }}${{ env.wxMSW_VER }}
      - uses: ilammy/msvc-dev-cmd@v1
      - name: start building wx widgtes
        run: |
          cd ${{ env.WXWIN }}${{ env.wxMSW_VER }}
          nmake /f makefile.vc BUILD=release TARGET_CPU=X86

#      - name: Install wxWidgets
#        run: |
#          mkdir ${env:WXWIN} | Out-Null
#          cd ${env:WXWIN}
#          curl -OL https://github.com/wxWidgets/wxWidgets/releases/download/v${env:wxMSW_VER}/wxWidgets-${env:wxMSW_VER}-headers.7z
#          7z x wxWidgets-${env:wxMSW_VER}-headers.7z
#          curl -OL https://github.com/wxWidgets/wxWidgets/releases/download/v${env:wxMSW_VER}/wxMSW-${env:wxMSW_VER}_vc14x_x64_Dev.7z
#          7z x wxMSW-${env:wxMSW_VER}_vc14x_x64_Dev.7z
#      - name: cmake
#        run: |
#          mkdir build
#          cd build
#          cmake .. -G "Visual Studio 16 2019" -A Win32 -DCMAKE_CONFIGURATION_TYPES=Release
#      - name: make
#        run: |
#          cd build
#          make
        
#  WindowsBuild:

#    runs-on: windows-latest
  
#    steps:
#      - uses: actions/checkout@v2
        
#      - name: Installing vcpkg (windows)
#        run: |
#          cd ..
#          git clone https://github.com/Microsoft/vcpkg.git
#          cd vcpkg
#          git checkout --force 2020.01
#          .\bootstrap-vcpkg.bat
#          .\vcpkg.exe install wxwidgets:x86-windows-static
##      - name: Download a file
##        uses: carlosperate/download-file-action@v1.0.3
##        id: download-poetry
##        with:
##            file-url: 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.4/wxWidgets-3.1.4.zip'
##            file-name: 'wxWidgets-3.1.4.zip'
##            location: './wxWidgets-3.1.4'
##      - name: Print the file path
##        run: echo "The file was downloaded to ${{ steps.download-poetry.outputs.file-path }}"

##      - name: Decompress
##        uses: TonyBogdanov/zip@1.0
##        with:
##            args: unzip -qq ./${{ steps.download-poetry.outputs.file-path }}/wxWidgets-3.1.4.zip -d ./wxwidgets
#      - name: cmake
#        run: |
#          mkdir build
#          cd build
#          cmake .. "-DCMAKE_TOOLCHAIN_FILE=D:/a/NaCl_Configurator/vcpkg/scripts/buildsystems/vcpkg.cmake" -G "Visual Studio 16 2019" -A Win32 -DCMAKE_CONFIGURATION_TYPES=Release
#      - name: make
#        run: |
#          cd build
#          make
